version: "3.8"

services:
  vit_train:
    build:
      context: .
      dockerfile: Dockerfile.new
    environment:
      - LOGGER_PORT=5000 # Specify the port for your Logger UI Server
    image: vit_train
    volumes:
      - ./logs:/workspace/logs
    restart: on-failure

  vit_tracking:
    image: ubuntu/mlflow:2.1.1_1.0-22.04
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/workspace/logs
    command: ["mlflow", "ui"]
    depends_on:
      - vit_train
